CREATE DATABASE IF NOT EXISTS dbms_project;
USE dbms_project;

SET SQL_SAFE_UPDATES = 0;

DROP TRIGGER IF EXISTS sub_quant;
DROP TRIGGER IF EXISTS add_quant;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS RETAIL;
DROP TABLE IF EXISTS QUANT;
DROP TABLE IF EXISTS TREATMENT;
DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS DOCTOR;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS DEALER;
DROP TABLE IF EXISTS STORES;
DROP TABLE IF EXISTS HOSPITAL;
DROP TABLE IF EXISTS MEDICINE;

SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE MEDICINE(
med_id INT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
composition VARCHAR(100),
mfg_date DATE NOT NULL,
exp_date DATE NOT NULL,
cost_per_tab INT,
CHECK(exp_date <= '2030-01-01'),
CHECK(mfg_date >= '2018-01-01')
);


CREATE TABLE STORES(
store_id VARCHAR(20) PRIMARY KEY,
name VARCHAR(50) NOT NULL,
address VARCHAR(100),
contact VARCHAR(20),
store_man VARCHAR(50)
);


CREATE TABLE DEALER(
dealer_id INT PRIMARY KEY,
name VARCHAR(50),
address VARCHAR(100),
phone VARCHAR(20)
);


CREATE TABLE HOSPITAL(
hos_id VARCHAR(20) PRIMARY KEY,
name VARCHAR(50),
address VARCHAR(100),
phone VARCHAR(20)
);


CREATE TABLE CONTRACT(
contract_id VARCHAR(20),
hos_id VARCHAR(20),
store_id VARCHAR(20),
PRIMARY KEY(hos_id,store_id),
FOREIGN KEY(hos_id) REFERENCES HOSPITAL(hos_id),
FOREIGN KEY(store_id) REFERENCES STORES(store_id)
);


CREATE TABLE DOCTOR(
doc_id INT,
hos_id VARCHAR(20),
doc_name VARCHAR(50),
PRIMARY KEY(doc_id,hos_id),
FOREIGN KEY(hos_id) REFERENCES HOSPITAL(hos_id)
);


CREATE TABLE PATIENT(
pat_id INT PRIMARY KEY,
name VARCHAR(50),
address VARCHAR(100),
phone VARCHAR(20)
);


CREATE TABLE RETAIL(
retail_id VARCHAR(20),
med_id INT,
store_id VARCHAR(20),
dealer_id INT,
batchno INT,
quantity_supplied INT,
PRIMARY KEY(retail_id,med_id,store_id,dealer_id),
CHECK(quantity_supplied <= 500),
FOREIGN KEY(med_id) REFERENCES MEDICINE(med_id) ON DELETE CASCADE,
FOREIGN KEY(store_id) REFERENCES STORES(store_id) ON DELETE CASCADE,
FOREIGN KEY(dealer_id) REFERENCES DEALER(dealer_id) ON DELETE CASCADE
);


CREATE TABLE TRANSACTIONS(
bill_id INT,
pat_id INT,
store_id VARCHAR(20),
med_id INT,
quantity INT,
pur_date DATE,
total INT,
PRIMARY KEY(bill_id,pat_id,med_id),
CHECK(quantity <=150),
FOREIGN KEY(pat_id) REFERENCES PATIENT(pat_id) ON DELETE CASCADE,
FOREIGN KEY(med_id) REFERENCES MEDICINE(med_id) ON DELETE CASCADE,
FOREIGN KEY(store_id) REFERENCES STORES(store_id) ON DELETE CASCADE
);


CREATE TABLE QUANT(
med_id INT,
store_id VARCHAR(20),
quantity INT,
PRIMARY KEY(med_id,store_id),
FOREIGN KEY(med_id) REFERENCES MEDICINE(med_id),
FOREIGN KEY(store_id) REFERENCES STORES(store_id)
);


CREATE TABLE TREATMENT(
treat_id INT,
pat_id INT,
hos_id VARCHAR(20),
doc_id INT,
treat_date DATE,
PRIMARY KEY(treat_id,pat_id,hos_id,doc_id),
FOREIGN KEY(pat_id) REFERENCES PATIENT(pat_id),
FOREIGN KEY(hos_id) REFERENCES HOSPITAL(hos_id),
FOREIGN KEY(doc_id,hos_id) REFERENCES DOCTOR(doc_id,hos_id)
);


DELIMITER //

CREATE TRIGGER add_quant
AFTER INSERT ON RETAIL
FOR EACH ROW
BEGIN
INSERT INTO QUANT(med_id,store_id,quantity)
VALUES(NEW.med_id,NEW.store_id,NEW.quantity_supplied)
ON DUPLICATE KEY UPDATE
quantity = quantity + NEW.quantity_supplied;
END//

CREATE TRIGGER sub_quant
AFTER INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
UPDATE QUANT
SET quantity = quantity - NEW.quantity
WHERE med_id = NEW.med_id
AND store_id = NEW.store_id;
END//

DELIMITER ;